apiVersion: v1
kind: Service
metadata:
  name: quickfood-backend-pagamento-service
  labels:
    app: quickfood-backend-pagamento
spec:
  type: LoadBalancer
  selector:
    app: quickfood-backend-pagamento
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80