apiVersion: v1
kind: Service
metadata:
  name: quickfood-backend-pedido-service
  labels:
    app: quickfood-backend-pedido
spec:
  type: LoadBalancer
  selector:
    app: quickfood-backend-pedido
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80