apiVersion: v1
kind: Service
metadata:
  name: quickfood-backend-sqlserver-service
  labels:
    app: quickfood-backend-sqlserver
spec:
  type: LoadBalancer
  selector:
    app: quickfood-backend-sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433