apiVersion: v1
kind: Service
metadata:
  name: quickfood-backend-producao-service
  labels:
    app: quickfood-backend-producao
spec:
  type: LoadBalancer
  selector:
    app: quickfood-backend-producao
  ports:
    - protocol: TCP
      port: 83
      targetPort: 80