apiVersion: v1
kind: Service
metadata:
  name: quickfood-backend-backoffice-service
  labels:
    app: quickfood-backend-backoffice
spec:
  type: LoadBalancer
  selector:
    app: quickfood-backend-backoffice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80