name: Deploy AWS Academy - EKS

on:
  workflow_run:
    workflows: ["Create Infra AWS"]
    types:
      - completed

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "EKS-QuickFood"

jobs:
  deploy:
    name: Deploy AWS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}